core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from dj_rest_auth.views import PasswordResetView, PasswordResetConfirmView
from dj_rest_auth.registration.views import VerifyEmailView, ResendEmailVerificationView
from densityAPI.views import NewEmailConfirmation




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stockright.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include('densityAPI.urls')),
    path('api/v1/auth/',  include('dj_rest_auth.urls')),
    path('api/v1/auth/register/', include('dj_rest_auth.registration.urls')),
    re_path(
        r'^api/v1/auth/register/account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(),
        name='account_confirm_email'),
    path('accounts/', include('allauth.urls')),
    path('api/v1/auth/resend-email/', NewEmailConfirmation.as_view(), name='resend_email_confirmation'),
    path('password-reset/', PasswordResetView.as_view(), name='rest_password_reset'),
    path('password/reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm',),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stockright/urls.py
from django.urls import path
from stockright import views

app_name = 'stockright'

urlpatterns = [
    path('', views.index, name="index"),
    path('ponds/', views.ponds, name='ponds'),
    path('ponds/<int:pond_id>', views.pond, name='pond'),
    path('new_pond', views.new_pond, name='new_pond'),
    path('ponds/delete/<int:pond_id>', views.delete_pond, name='delete_pond'),
    path('ponds/<int:pond_id>/edit', views.edit_pond_name, name='edit_pond_name'),
    path('check_stock/<int:pond_id>', views.check_stock, name='check_stock'),
    path('edit/<int:stock_id>', views.edit_density, name='edit_density'),
    path('delete/<int:stock_id>', views.delete_density, name='delete_density'),

]

users/urls.py
from django.urls import path,reverse_lazy
from users import views
from django.contrib.auth import views as auth_views



app_name = 'users'

urlpatterns = [    
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("password-change/", 
        auth_views.PasswordChangeView.as_view(success_url='done'),
        name="password_change"),
    path("password-change/done/", 
        auth_views.PasswordChangeDoneView.as_view(), 
        name="password_change_done"),
    path("password-reset/", 
        auth_views.PasswordResetView.as_view(
            template_name='registration/my_password_reset_form.html',
            success_url='done'), 
        name="password_reset"),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password_reset_complete')),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('register/', views.register, name='register'),
]

stockright/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from common.models import BaseModel





class CustomUser(AbstractUser):

    email_address_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.username

class Profile(BaseModel):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.CASCADE,
        related_name='user_profile',
    )
    firstname = models.CharField(max_length=50, null=True)
    lastname = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)

    def __str__(self):
        return "%s %s" % (self.firstname, self.lastname)

class Pond(BaseModel):
    '''Pond types'''
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='ponds')

    def __str__(self):
        return self.name



# Create your models here.
class StockingDensity(BaseModel):
    pond = models.ForeignKey(Pond, on_delete=models.CASCADE)
    length = models.FloatField()
    width = models.FloatField()
    height = models.FloatField()
    to_stock = models.FloatField()
    verdict = models.TextField(null=True, blank=True)
    twenty_percent_decrease = models.FloatField()
    thirty_percent_decrease = models.FloatField()


    class Meta:
        ordering = ['-date_added']
        verbose_name = 'stocking density'
        verbose_name_plural = 'stocking densities'

    def __str__(self):
        return f"{self.length} by {self.width} by {self.height}"

stockright/forms.py
from django import forms
from stockright.models import StockingDensity, Pond
from django.utils.translation import gettext_lazy as _

class DensityForm(forms.ModelForm):
    class Meta:
        model = StockingDensity
        fields = ['length', 'width', 'height']
        labels = {'length': 'Length in feet', 'width':'Width in feet', 'height':'Height in feet',}
    
    def clean_length(self):
        length = self.cleaned_data.get('length')
        if length is not None and length <= 0:
            raise forms.ValidationError(_('Length must be a positive value and not zero.'))
        return length
    
    def clean_width(self):
        width = self.cleaned_data.get('width')
        if width is not None and width <= 0:
            raise forms.ValidationError(_('Width must be a positive value and not zero.'))
        return width
    
    def clean_height(self):
        height = self.cleaned_data.get('height')
        if height is not None and height <= 0:
            raise forms.ValidationError(_('Height must be a positive value and not zero.'))
        return height




#Model Pond form
class PondForm(forms.ModelForm):
    class Meta:
        model = Pond
        fields = ['name']
        label = {'name': 'Enter a pond name'}

stockright/views.py
from django.shortcuts import render, get_object_or_404
from stockright.models import StockingDensity, Pond
from stockright.forms import DensityForm, PondForm
from stockright.pond_logic import pondvolume, thirty_p_decrease, twenty_p_decrease
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    return render(request, 'stockright/index.html')

@login_required
def ponds(request):
    '''show all ponds of a single user'''
    pond_type = Pond.objects.filter(owner=request.user).order_by('name')
    context = {'pond_type':pond_type}
    return render(request, 'stockright/ponds.html', context)

@login_required
def pond(request, pond_id):
    # pond = Pond.objects.get(id=pond_id)
    # if pond.owner != request.user:
    #     raise Http404
    pond = get_object_or_404(Pond, owner=request.user, id=pond_id)
    densities = pond.stockingdensity_set.order_by('-date_checked')
    context = {'pond':pond, 'densities':densities}
    return render(request, 'stockright/pond.html', context)

@login_required
def new_pond(request):
    '''create a new pond'''
    if request.method != 'POST':
        form = PondForm()
    else:
        form = PondForm(data=request.POST)
        if form.is_valid():
            pond_name = form.cleaned_data['name']
            if Pond.objects.filter(owner=request.user, name__icontains=pond_name).exists():
                form.add_error('name', 'A pond with this name already exists.')
            else:
                new_pond = form.save(commit=False)
                new_pond.owner = request.user
                new_pond.save()
                return HttpResponseRedirect(reverse('stockright:ponds'))
    context={'form':form}
    return render(request, 'stockright/crud/add_pond.html', context)

@login_required
def edit_pond_name(request, pond_id):
    pond = Pond.objects.get(id=pond_id)
    name = pond.name
    if pond.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = PondForm(instance=pond)
    else:
        form = PondForm(instance=pond, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('stockright:ponds'))
    context = {'pond':pond, 'name':name, 'form':form}
    return render(request, 'stockright/crud/edit_pond_name.html', context)

@login_required
def delete_pond(request, pond_id):
    pond = Pond.objects.get(id=pond_id)
    owner = pond.owner
    if owner != request.user:
        raise Http404
    pond.delete()
    return HttpResponseRedirect(reverse('stockright:ponds'))

@login_required
def check_stock(request, pond_id):
    pond = Pond.objects.get(id=pond_id)
    if request.method != 'POST':
        form = DensityForm()
    else:
        form = DensityForm(data=request.POST)
        if form.is_valid():
            new_check = form.save(commit=False)
            new_check.pond = pond
            new_check.to_stock = pondvolume(new_check.length, new_check.width, new_check.height)
            new_check.verdict = f'You can humbly stock {new_check.to_stock} fishes.'
            new_check.twenty_percent_decrease = twenty_p_decrease(new_check.to_stock)
            new_check.thirty_percent_decrease = thirty_p_decrease(new_check.to_stock)
            new_check.save()
            return HttpResponseRedirect(reverse('stockright:pond', args=[pond.id]))
    context = {'pond':pond,'form':form}
    return render(request, 'stockright/check_stock.html', context)

@login_required
def edit_density(request, stock_id):
    density = StockingDensity.objects.get(id=stock_id)
    pond = density.pond
    if pond.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = DensityForm(instance=density)
    else:
        form = DensityForm(instance=density, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('stockright:pond', args=[pond.id]))
    context = {'density':density, 'pond':pond, 'form':form}
    return render(request, 'stockright/crud/edit_density.html', context)


@login_required
def delete_density(request, stock_id):
    density = StockingDensity.objects.get(id=stock_id)
    owner = density.pond.owner
    if owner != request.user:
        raise Http404
    density.delete()
    return HttpResponseRedirect(reverse('stockright:pond', args=[density.pond.id]))


  

stockright/templates/stockright/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stocking Density</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'stockright:index' %}">Home</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
        {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav">
            <li><a href="{% url 'stockright:ponds' %}">Ponds</a></li>
          </ul>    
          <ul class="nav navbar-nav navbar-right">   
            <li><a>Hello {{ request.user.username }}</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'users:login' %}">Login</a></li>
            <li><a href="{% url 'users:register' %}">Register</a></li>
          </ul>
        {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!-- /container -->
  </body>
</html>

stockright/templates/stockright/check_stock.html
{% extends 'stockright/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h3><a href="{% url 'stockright:pond' pond.id %}"><< Back to {{ pond }} dimensions</a></h3>
{% endblock header %}

{% block content %}
<form action="{% url 'stockright:check_stock' pond.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-primary">Check Stocking</button>
    {% endbuttons %}
</form>

{% endblock content %}

stockright/templates/stockright/index.html
{% extends 'stockright/base.html' %}

{% block header %}
    <div class="jumbotron">
        <h1>Check your pond stocking capacity</h1>
    </div>
{% endblock header %}

{% block content %}
    {% if user.is_authenticated %}
    <h3>
        <a href="{% url 'stockright:ponds' %}"><em>Select from list of ponds or create a new pond</em></a>
    </h3>
    {% else %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to check your stocking capacity
    </h2>
    {% endif %}
{% endblock content %}

stockright/templates/stockright/pond.html
{% extends 'stockright/base.html' %}

{% block header %}
    <h1><a href="{% url 'stockright:ponds' %}">{{ pond|title }}</a></h1>   
{% endblock header %}

{% block content %}
    {% if not densities %} 
        <li>There are no dimensions for this pond.</li>
    {% else %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Dimensions</h3>
        </div>
        <table class="table">
            <tr>
                <th>Pond Type</th>
                <th>Length</th>
                <th>Width</th>
                <th>Height</th>
                <th>Quantity to Stock</th>
                <th>Recommendation</th>
                <th>20% Decrease</th>
                <th>30% Decrease</th>
                <th>Date Checked</th>
            </tr>
            {% for density in densities %}
            <tr>
                <td>{{ density.pond.name }}</td>
                <td>{{ density.length }}</td>
                <td>{{ density.width }}</td>
                <td>{{ density.height }}</td>
                <td>{{ density.to_stock }}</td>
                <td>{{ density.verdict }}</td>
                <td>{{ density.twenty_percent_decrease }}</td>
                <td>{{ density.thirty_percent_decrease }}</td>
                <td>{{ density.date_checked|date:'M d, Y H:i'}}</td>
                <td><a href="{% url 'stockright:delete_density' density.id %}">Delete</a></td>
                <td><a href="{% url 'stockright:edit_density' density.id %}">Edit</a></td>
            </tr>
            {% endfor%}  
        </table>
    </div>
    {% endif %}
    
    <p>
        <a href="{% url 'stockright:check_stock' pond.id %}">Check new pond dimension</a>
    </p>
{% endblock content %}

stockright/templates/stockright/ponds.html
{% extends 'stockright/base.html' %}

{% block header %}
    <h1>Ponds</h1>
{% endblock header %}

{% block content %}
    <ul>
    {% for pond in pond_type %}
        <li>
            <h3>
                <a href="{% url 'stockright:pond' pond.id %}">{{ pond.name|title }}</a>
            </h3>
            <a href="{% url 'stockright:edit_pond_name' pond.id %}"><small><em>Edit pond</em></small></a> |
            <a href="{% url 'stockright:delete_pond' pond.id %}"><small><em>Delete pond</em></small></a>
        </li>
    {% empty %}
        <li>No ponds created yet</li>
    {% endfor %}
    </ul>
    <h3><a href="{% url 'stockright:new_pond' %}">Create new pond</a></h3>

{% endblock content %}